### ISSUE TITLE
bower and npm packages

### ISSUE THREAD

**Issue by JohnnyTheTank** [enkidootech/xml2json#1]
Hello,

I'm planning to create a [xml loader plugin](https://github.com/JohnnyTheTank/apiNG-plugin-xmlloader) for **[apiNG](https://github.com/JohnnyTheTank/apiNG)**. For this, I want to use your module. I need a bower or npm package, for adding this modules to the dependencies.

Here is tutorial for adding a repo to npm: https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-publishing-to-npm

Is this possible?
Thanks a lot!

**Comment by pmantryvong** [comment]
Hello, do you still us to put that on NPM?

**Comment by SamuelEnkidoo** [comment]
Hello, I've just published the package on npmjs if you still need it : https://www.npmjs.com/package/xml2json-light

Have fun building your plugin!

**Comment by JohnnyTheTank** [comment]
thats great. thank you!
