### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by arjunu** [enkidootech/xml2json#2]
I was reading a huge xml file (about 5000 lines) and I got this:

/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:60
    xmlStr = xmlStr.replace(/\n|\t|\r/g, ''); //replace special characters
                    ^

RangeError: Maximum call stack size exceeded
    at String.replace (native)
    at cleanXML (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:60:21)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:12:14)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)
    at xml2json (/Users/arjunu/WebstormProjects/ConfigCompare/node_modules/xml2json-light/xml2json.js:33:23)

**Comment by enkidoo** [comment]
Thank you for raising this issue. It will  be addressed as soon as possible.

**Comment by LaurenceAmyotte** [comment]
Could you provide us with a bit more details? Is your application client side or server side? If it is client side, in what browser do you encounter this issue? If its possible for you to provide us with the xml you are using, contact me via email.

**Comment by arjunu** [comment]
It's a node app I was making to parse and compare XMLs. Sorry I can't share the xml as it contains client data.

**Comment by LaurenceAmyotte** [comment]
Hi, I managed to recreate the error you are having. I can confirm that it is no related to the size of the xml file you are providing (I tested with 6000+ lines). It is related to its structure. 

The converter expects xml of the format : 
```xml
 <name>
   <firstName> Jane </firstName>
   <lastName> Doe </lastName>
 </name>
```
This would return : 
```json
{
    "name": {
        "firstName": "Jane",
        "lastName": "Doe"
    }
}
```
You could also parse : 
```xml
 <name>
   <firstName> Jane </firstName>
   <firstName> John </firstName>
   <lastName> Doe </lastName>
 </name>
```
This would return : 
```json
{
    "name": {
        "firstName": ["Jane", "John"],
        "lastName": "Doe"
    }
}
```

However, in the current version, you cannot parse xml with this structure :  
```xml
 <name>
   <firstName> Jane </firstName>
   <lastName> Doe </lastName>
   <name> Jane Doe </name>
 </name>
```
Here, a the parent "name" has a child attribute also called "name". This will cause the error : 
```RangeError: Maximum call stack size exceeded```
This is not an xml error but the logic here would be wrong as the child "name" should not be the same as its parent as they are 2 distinct objects.

Could you confirm that a similar case is present in your xml file? If so, could you post it or send it to me via email (without the actual client data) as an example of a use case to help us implement this new feature? 
If not, do you have anything in your xml file that looks like it could create problems of the same nature?

**Comment by arjunu** [comment]
I figured it out. In my case it wasn't that. I started deleting nodes from the XML until I found the part that was causing the error. Buried somewhere in the 5000+ lines was a comment line: 
` <!-- Comment text -->`

**Comment by LaurenceAmyotte** [comment]
Thank you for the follow-up. Glad it worked out.

**Comment by arjunu** [comment]
But the parse should support XMLs with comments shouldn't it?

**Comment by LaurenceAmyotte** [comment]
I added this new feature (npm was also updated). The comments should not cause anymore problems as they will be removed as follows : 
```javascript
var parser = require('xml2json-light');
var xml = '<name> <!-- some comment --> Jane Doe </name>';
// The xml string is converted to : 
// <name> Jane Doe </name>
// All comments will be removed 
var json = parser.xml2json(xml); 
console.log(json); 
// prints ‘{"name": "Jane Doe"}’
```
Please give it a try and tell us if this is what you needed.

**Comment by arjunu** [comment]
Yes it is working fine now with 1.0.4. Thanks!
